# kubectl apply -k forum-pipe/forum-gitops/php-app/forum-yaml/
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: forum

resources:
  - namespace.yaml
  - pv.yaml
  - pvc.yaml
  - secret.yaml
  - mysql-deployment.yaml
  - mysql-service.yaml
  - laravel-deployment.yaml
  - laravel-service.yaml
  - nginx-configmap.yaml
  - nginx-deployment.yaml
  - nginx-service.yaml
  - ingress.yaml
  - laravel-hpa.yaml
  - network-policy.yaml
