apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  namespace: forum
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: laravel-secrets
                  key: db_root
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: laravel-secrets
                  key: db_name
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: laravel-secrets
                  key: db_user
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: laravel-secrets
                  key: db_password
          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: mysql-pvc
