apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  namespace: forum
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 192.168.245.153
    path: /srv/nfs/mysql
  persistentVolumeReclaimPolicy: Retain
